export const Types = {
  // LOGIN
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  CHECK_LOGIN_FINISH: "CHECK_LOGIN_FINISH",
  CHECK_RECOVERY_STATUS: "CHECK_RECOVERY_STATUS",
  CHANGE_PASSWORD: "CHANGE_PASSWORD",

  //UI
  UI_OPEN_MENU: "UI_OPEN_MENU",
  UI_CLOSE_MENU: "UI_CLOSE_MENU",
  UI_OPEN_MODAL: "UI_OPEN_MODAL",
  UI_CLOSE_MODAL: "UI_CLOSE_MODAL",

  //ADMINISTRATOR
  ADMINISTRATORS_LOADED: "ADMINISTRATORS_LOADED",

  //COLLABORATOR
  COLLABORATORS_LOADED: "COLLABORATORS_LOADED",
  COLLABORATOR_COUNT: "COLLABORATOR_COUNT",
  ADD_NEW_COLLABORATOR: "ADD_NEW_COLLABORATOR",

  //pagos
  PAYMENTS_LOADED: "PAYMENTS_LOADED",

  //PRESTAMOS
  LENDS_LOADED: "LENDS_LOADED",
  LENDS_LOADED_BY_COLLABORATOR: "LENDS_LOADED_BY_COLLABORATOR", 
  FEES_LOADED: "FEES_LOADED",

  //CONTRATOS
  CONTRACTS_ACTIVES_LOADED: "CONTRACTS_ACTIVES_LOADED",
};
