export const Types = {
  // LOGIN
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  CHECK_LOGIN_FINISH: "CHECK_LOGIN_FINISH",
  CHECK_RECOVERY_STATUS: "CHECK_RECOVERY_STATUS",
  CHANGE_PASSWORD: "CHANGE_PASSWORD",

  //UI
  UI_OPEN_MENU: "UI_OPEN_MENU",
  UI_CLOSE_MENU: "UI_CLOSE_MENU",
  UI_OPEN_MODAL_ADMINISTRATOR: "UI_OPEN_MODAL_ADMINISTRATOR",
  UI_CLOSE_MODAL_ADMINISTRATOR: "UI_CLOSE_MODAL_ADMINISTRATOR",
  UI_OPEN_MODAL_COLLABORATOR: "UI_OPEN_MODAL_COLLABORATOR",
  UI_CLOSE_MODAL_COLLABORATOR: "UI_CLOSE_MODAL_COLLABORATOR",
  UI_OPEN_MODAL_JOBS: "UI_OPEN_MODAL_JOBS",
  UI_CLOSE_MODAL_JOBS: "UI_CLOSE_MODAL_JOBS",
  UI_OPEN_MODAL_FEES: "UI_OPEN_MODAL_FEES",
  UI_CLOSE_MODAL_FEES: "UI_CLOSE_MODAL_FEES",
  UI_OPEN_MODAL_ADD_LEND: "UI_OPEN_MODAL_ADD_LEND",
  UI_CLOSE_MODAL_ADD_LEND: "UI_CLOSE_MODAL_ADD_LEND",
  UI_OPEN_MODAL_ADD_TOOL: "UI_OPEN_MODAL_ADD_TOOL",
  UI_CLOSE_MODAL_ADD_TOOL: "UI_CLOSE_MODAL_ADD_TOOL",
  UI_OPEN_MODAL_ACTIVES: "UI_OPEN_MODAL_ACTIVES",
  UI_CLOSE_MODAL_ACTIVES: "UI_CLOSE_MODAL_ACTIVES",
  UI_OPEN_MODAL_PAYMENT: "UI_OPEN_MODAL_PAYMENT",
  UI_CLOSE_MODAL_PAYMENT: "UI_CLOSE_MODAL_PAYMENT",

  //ADMINISTRATOR
  ADMINISTRATORS_LOADED: "ADMINISTRATORS_LOADED",
  ADD_NEW_ADMINISTRATOR: "ADD_NEW_ADMINISTRATOR",
  ADMINISTRATOR_SET_ACTIVE: "ADMINISTRATOR_SET_ACTIVE",
  ADMINISTRATOR_CLEAR_ACTIVE: "ADMINISTRATOR_CLEAR_ACTIVE",

  //COLLABORATOR
  COLLABORATORS_LOADED: "COLLABORATORS_LOADED",
  COLLABORATOR_COUNT: "COLLABORATOR_COUNT",
  ADD_NEW_COLLABORATOR: "ADD_NEW_COLLABORATOR",
  COLLABORATOR_SET_ACTIVE: "COLLABORATOR_SET_ACTIVE",
  COLLABORATOR_CLEAR_ACTIVE: "COLLABORATOR_CLEAR_ACTIVE",
  UI_OPEN_MODAL_COLLABORATOR_INFO: "UI_OPEN_MODAL_COLLABORATOR_INFO",
  UI_CLOSE_MODAL_COLLABORATOR_INFO: "UI_CLOSE_MODAL_COLLABORATOR_INFO",
  VALIDATE_PRESENCE_COLLABORATOR: "VALIDATE_PRESENCE_COLLABORATOR",

  //ANIMALES
  ANIMALS_LOADED: "ANIMALS_LOADED",

  //TRABAJOS
  JOB_LOADED: "JOB_LOADED",
  ADD_JOB: "ADD_JOB",
  DELETE_JOB: "DELETE_JOB",
  JOB_SET_ACTIVE: "JOB_SET_ACTIVE",
  JOB_CLEAR_ACTIVE: "JOB_CLEAR_ACTIVE",

  //pagos
  PAYMENTS_LOADED: "PAYMENTS_LOADED",
  REGISTER_PRESENCE_SUCCESS: "REGISTER_PRESENCE_SUCCESS",
  CLEAN_PRESENCE_DAY_BY_COLLABORATOR: "CLEAN_PRESENCE_DAY_BY_COLLABORATOR",

  //PRESTAMOS
  LENDS_LOADED: "LENDS_LOADED",
  LENDS_LOADED_BY_COLLABORATOR: "LENDS_LOADED_BY_COLLABORATOR",
  ADD_NEW_LEND: "ADD_NEW_LEND",
  LEND_SET_ACTIVE: "LEND_SET_ACTIVE",
  LEND_CLEAR_ACTIVE: "LEND_CLEAR_ACTIVE",
  LEND_CHANGE_FEE: "LEND_CHANGE_FEE",
  PRESENCE_DAY_BY_COLLABORATOR_LOADED: "PRESENCE_DAY_BY_COLLABORATOR_LOADED",

  //CUOTAS
  FEES_LOADED: "FEES_LOADED",
  FEE_LOADED_CLEAR: "FEE_LOADED_CLEAR",
  ADD_NEW_FEE: "ADD_NEW_FEE",
  ADD_FEE_SUCCESS: "ADD_FEE_SUCCESS", //TALVEZ NO SE OCUPE
  ADD_FEE_ERROR: "ADD_FEE_ERROR", //TALVEZ NO SE OCUPE

  //CONTRATOS
  CONTRACTS_ACTIVES_LOADED: "CONTRACTS_ACTIVES_LOADED",

  //HERRAMIENTAS
  TOOLS_LOADED: "TOOLS_LOADED",
  ADD_NEW_TOOL: "ADD_NEW_TOOL",
  ADD_TO_SELECT_TOOLS: "ADD_TO_SELECT_TOOLS",
  REMOVE_IN_SELECT_TOOLS: "REMOVE_IN_SELECT_TOOLS",
  CLEAN_SELECT_TOOLS: "CLEAN_SELECT_TOOLS",

  //Activos
  ACTIVES_LOADED: "ACTIVES_LOADED",
  REMOVE_IN_ACTIVES: "REMOVE_IN_ACTIVES",
  ADD_TO_SELECT_ACTIVES: "ADD_TO_SELECT_ACTIVES",
  REMOVE_IN_SELECT_ACTIVES: "REMOVE_IN_SELECT_ACTIVES",
  CLEAN_SELECT_ACTIVES: "CLEAN_SELECT_ACTIVES",
};
